// src/components/Styles.js

// Variáveis de suporte (sem alterar a estrutura original)
const COLORS = {
  primary: "#ff5252",
  secondary: "#4caf50",
  dark: "#1a1a1a",
  white: "#ffffff",
  blue: "#2196F3",
  yellow: "#ffcc00",
  grey10: "#e7e7e7",
  grey25: "#CCCCCC",
  grey50: "#888888",
  grey75: "#333333",
  textMain: "#444444",
  textMuted: "#666666",
  shadow: "rgba(0,0,0,0.4)",
};

const FONT_FAMILY = "'Segoe UI', Roboto, sans-serif";

export const commonStyles = {
  container: {
    maxWidth: "1200px",
    margin: "40px auto",
    padding: "0 20px",
    fontFamily: FONT_FAMILY,
  },
  column: {
    flex: "1",
    minWidth: "250px",
  },
  header: { textAlign: "center", marginBottom: "40px" },
  title: { fontSize: "32px", color: COLORS.textMain, marginBottom: "10px" },
  subtitle: { fontSize: "18px", color: COLORS.textMuted },
  grid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "20px",
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: "12px",
    padding: "25px",
    width: "280px",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
    borderTop: `5px solid ${COLORS.primary}`,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    transition: "transform 0.2s",
  },
  cardTitle: { margin: 0, color: COLORS.dark, fontSize: "18px" },
  cardText: {
    margin: 0,
    color: COLORS.grey75,
    lineHeight: "1.5",
    fontSize: "14px",
  },
  viewBtn: {
    marginTop: "10px",
    padding: "8px",
    backgroundColor: COLORS.secondary,
    color: COLORS.white,
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
  },

  contentWrapper: {
    backgroundColor: COLORS.white,
    padding: "30px",
    borderRadius: "12px",
    marginTop: "20px",
    marginBottom: "20px",
    lineHeight: "1.8",
    fontSize: "16px",
    color: COLORS.grey75,
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
};

export const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.shadow,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2000,
    padding: "20px",
  },
  content: {
    backgroundColor: COLORS.white,
    padding: "30px",
    borderRadius: "12px",
    maxWidth: "500px",
    width: "100%",
    position: "relative",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
    maxHeight: "90vh",
    overflowY: "auto",
  },
  closeBtn: {
    position: "absolute",
    top: "15px",
    right: "15px",
    border: "none",
    background: "none",
    fontSize: "20px",
    cursor: "pointer",
    color: COLORS.textMuted,
  },
  sectionTitle: {
    borderBottom: `2px solid ${COLORS.secondary}`,
    paddingBottom: "5px",
    marginTop: "20px",
    color: COLORS.textMain,
  },
  list: { paddingLeft: "20px", lineHeight: "1.8", color: COLORS.grey75 },
  text: { lineHeight: "1.6", color: COLORS.grey75 },
};

export const footerStyles = {
  footer: {
    backgroundColor: COLORS.dark,
    color: COLORS.grey25,
    padding: "40px 0 0 0",
    marginTop: "60px",
    borderTop: `3px solid ${COLORS.primary}`,
    fontFamily: FONT_FAMILY,
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    padding: "0 20px",
    gap: "30px",
  },
  column: { flex: "1", minWidth: "250px" },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "15px",
  },
  logoImg: { height: "35px", width: "auto" },
  logoText: { color: COLORS.primary, fontSize: "20px", fontWeight: "bold" },
  description: { fontSize: "14px", lineHeight: "1.6" },
  heading: {
    color: COLORS.white,
    fontSize: "16px",
    marginBottom: "15px",
    textTransform: "uppercase",
  },
  nav: { display: "flex", flexDirection: "column", gap: "10px" },
  link: {
    color: COLORS.grey25,
    textDecoration: "none",
    fontSize: "14px",
    transition: "color 0.2s",
  },
  socialRow: { marginTop: "10px" },
  socialIcon: {
    color: COLORS.primary,
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "bold",
  },
  bottomBar: {
    borderTop: `1px solid ${COLORS.grey75}`,
    marginTop: "40px",
    padding: "20px",
    textAlign: "center",
  },
  copyright: { fontSize: "12px", color: COLORS.textMuted, margin: 0 },
};

export const loginStyles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "85vh",
    fontFamily: FONT_FAMILY,
    backgroundColor: COLORS.grey10,
  },
  card: {
    background: COLORS.white,
    padding: "30px",
    borderRadius: "12px",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
    textAlign: "center",
    maxWidth: "380px",
    width: "90%",
  },
  titulo: { color: COLORS.textMain, marginBottom: "20px", fontSize: "24px" },
  googleBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    width: "100%",
    padding: "12px",
    backgroundColor: COLORS.white,
    border: `1px solid ${COLORS.grey25}`,
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "600",
    color: COLORS.grey75,
    marginBottom: "15px",
  },
  divisor: {
    borderBottom: `1px solid ${COLORS.grey10}`,
    lineHeight: "0.1em",
    margin: "20px 0",
  },
  divisorTexto: {
    background: COLORS.white,
    padding: "0 10px",
    color: COLORS.grey50,
    fontSize: "13px",
  },
  form: { display: "flex", flexDirection: "column", gap: "12px" },
  input: {
    padding: "12px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.grey25}`,
    fontSize: "15px",
  },
  submitBtn: {
    padding: "12px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    marginTop: "5px",
  },
  alerta: {
    padding: "10px",
    borderRadius: "6px",
    fontSize: "14px",
    marginBottom: "15px",
  },
  footer: { marginTop: "20px", fontSize: "14px" },
  toggleText: { color: COLORS.textMuted, marginBottom: "15px" },
  toggleLink: { color: COLORS.primary, fontWeight: "bold", cursor: "pointer" },
  backLink: {
    color: COLORS.grey50,
    textDecoration: "none",
    display: "block",
    marginTop: "10px",
  },
};

export const headerStyles = {
  header: {
    backgroundColor: COLORS.dark,
    color: COLORS.white,
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
    position: "sticky",
    top: 0,
    zIndex: 1000,
    fontFamily: FONT_FAMILY,
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 20px",
    height: "70px",
  },
  leftSection: { display: "flex", alignItems: "center", gap: "30px" },
  logoLink: {
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  logoImg: {
    height: "100px",
    width: "auto",
    display: "block",
    marginTop: "30px",
  },
  logoText: { fontSize: "22px", fontWeight: "bold", color: COLORS.primary },
  mainNav: { display: "flex", gap: "20px" },
  navLink: {
    color: COLORS.grey25,
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  rightSection: { display: "flex", alignItems: "center", gap: "20px" },
  userSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "15px",
  },
  profile: { display: "flex", alignItems: "center", gap: "10px" },
  avatar: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    border: `2px solid ${COLORS.primary}`,
    objectFit: "cover",
  },
  userName: { fontSize: "14px", fontWeight: "600", color: COLORS.white },
  adminLink: {
    color: COLORS.yellow,
    textDecoration: "none",
    fontSize: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    border: `1px solid ${COLORS.yellow}`,
    padding: "5px 10px",
    borderRadius: "4px",
  },
  logoutBtn: {
    backgroundColor: COLORS.grey75,
    color: COLORS.white,
    border: `1px solid ${COLORS.grey75}`,
    padding: "6px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "500",
  },
  hamburger: {
    background: "none",
    border: "none",
    color: "white",
    fontSize: "28px",
    cursor: "pointer",
  },
  mobileMenu: {
    position: "absolute",
    top: "70px",
    left: 0,
    width: "100%",
    backgroundColor: COLORS.dark,
    display: "flex",
    flexDirection: "column",
    padding: "20px",
    gap: "15px",
    borderTop: `1px solid ${COLORS.grey75}`,
  },
  mobileNavLink: {
    color: "white",
    textDecoration: "none",
    fontSize: "16px",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  divider: { width: "100%", borderColor: COLORS.grey75, margin: "5px 0" },
  mobileMenuBtn: {
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    border: "none",
    padding: "12px",
    borderRadius: "4px",
    fontWeight: "bold",
    cursor: "pointer",
    width: "50%",
  },
  loginBtn: {
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    textDecoration: "none",
    padding: "8px 20px",
    borderRadius: "4px",
    fontWeight: "bold",
  },
  dropdownContainer: { position: "relative", display: "inline-block" },
  adminDropdownBtn: {
    backgroundColor: COLORS.grey75,
    color: COLORS.yellow,
    border: `1px solid ${COLORS.yellow}`,
    padding: "8px 15px",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  dropdownMenu: {
    position: "absolute",
    top: "90%",
    right: 0,
    backgroundColor: COLORS.grey75,
    minWidth: "180px",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
    borderRadius: "4px",
    zIndex: 1100,
    padding: "5px 0",
    border: `1px solid ${COLORS.textMain}`,
    marginTop: "5px",
  },
  dropdownItem: {
    color: COLORS.white,
    padding: "12px 16px",
    textDecoration: "none",
    display: "block",
    fontSize: "14px",
    transition: "background 0.2s",
    textAlign: "left",
  },
  dropdownDivider: {
    height: "1px",
    backgroundColor: COLORS.grey75,
    margin: "5px 0",
  },
};

export const adminStyles = {
  tabBar: {
    display: "flex",
    gap: "5px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  tabBtn: {
    padding: "10px 15px",
    border: "none",
    color: "white",
    cursor: "pointer",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: "bold",
  },
  label: {
    fontSize: "12px",
    fontWeight: "bold",
    marginBottom: "5px",
    color: COLORS.textMain,
    display: "block",
  },
  input: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.grey25}`,
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.grey25}`,
    minHeight: "80px",
    boxSizing: "border-box",
  },
  msgStyle: {
    position: "fixed",
    top: "20px",
    right: "20px",
    backgroundColor: COLORS.secondary,
    color: "white",
    padding: "15px 25px",
    borderRadius: "8px",
    zIndex: 4000,
    fontWeight: "bold",
  },
  cardBox: {
    background: COLORS.grey10,
    padding: "15px",
    borderRadius: "8px",
    marginBottom: "15px",
    border: `1px solid ${COLORS.grey10}`,
  },
  deleteBtn: {
    color: "red",
    border: "none",
    background: "none",
    cursor: "pointer",
    fontSize: "12px",
    marginTop: "5px",
  },
  flexRowSpace: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  flexRowGap: { display: "flex", gap: "10px", marginBottom: "10px" },
  recipeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginTop: "5px",
  },
  headerActions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "10px",
  },
  addBtn: {
    backgroundColor: COLORS.blue,
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    fontWeight: "bold",
    cursor: "pointer",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
  userCard: {
    ...commonStyles.card,
    width: "320px",
    flexDirection: "row",
    alignItems: "center",
    gap: "15px",
    padding: "15px",
    borderTop: "none",
    borderLeft: `5px solid ${COLORS.primary}`,
  },
  avatarWrapper: { width: "50px", height: "50px", flexShrink: 0 },
  avatarImg: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    objectFit: "cover",
    border: `1px solid ${COLORS.grey25}`,
  },
  userInfo: { flex: 1, minWidth: 0 },
  userName: {
    margin: 0,
    fontSize: "15px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    color: COLORS.grey75,
  },
  userEmail: {
    margin: "2px 0",
    fontSize: "12px",
    color: COLORS.textMuted,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  inactiveText: { color: COLORS.primary, textDecoration: "line-through" },
  badgeRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    marginTop: "5px",
  },
  roleBadge: {
    fontSize: "9px",
    padding: "2px 6px",
    borderRadius: "10px",
    color: "white",
    fontWeight: "bold",
  },
  statusText: { fontSize: "10px", color: COLORS.grey50 },
  actionCol: { display: "flex", flexDirection: "column", gap: "8px" },
  iconBtn: {
    background: COLORS.grey10,
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    padding: "6px",
    fontSize: "14px",
  },
  deleteIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "16px",
    padding: "4px",
  },
  modalForm: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginTop: "15px",
  },
  select: {
    padding: "10px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.grey25}`,
    backgroundColor: COLORS.white,
    fontSize: "14px",
  },
  btnGroup: { display: "flex", gap: "10px", marginTop: "10px" },
  saveBtn: {
    flex: 2,
    padding: "12px",
    backgroundColor: COLORS.secondary,
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  cancelBtn: {
    flex: 1,
    padding: "12px",
    backgroundColor: COLORS.textMuted,
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },
  infoText: {
    fontSize: "13px",
    color: COLORS.primary,
    fontWeight: "bold",
    margin: "5px 0",
  },
  modalInfo: { fontSize: "14px", color: COLORS.textMain, marginBottom: "10px" },
  divBtnSalvar: { padding: "20px 0" },
  headerRow: {
    ...commonStyles.header,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
  },
  shortcutsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "20px",
    marginTop: "30px",
  },
  shortcutCard: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
    padding: "20px",
    backgroundColor: COLORS.grey10,
    borderRadius: "10px",
    textDecoration: "none",
    color: "inherit",
    border: `1px solid ${COLORS.grey10}`,
    transition: "transform 0.2s, box-shadow 0.2s",
    cursor: "pointer",
  },
  shortcutInfo: {
    display: "flex",
    flexDirection: "column",
  },
  shortcutTitle: {
    fontSize: "16px",
    color: COLORS.grey75,
  },
  shortcutDesc: {
    fontSize: "13px",
    color: COLORS.textMuted,
    margin: 0,
  },
  icon: {
    fontSize: "24px",
    backgroundColor: COLORS.white,
    padding: "10px",
    borderRadius: "8px",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
  loading: { padding: "100px", textAlign: "center", color: COLORS.textMuted },
  toast: {
    position: "fixed",
    top: "20px",
    right: "20px",
    background: COLORS.secondary,
    color: "white",
    padding: "15px 25px",
    borderRadius: "8px",
    zIndex: 5000,
    fontWeight: "bold",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
  headerButtons: { display: "flex", gap: "10px" },
  saveAllBtn: {
    padding: "10px 20px",
    background: COLORS.secondary,
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  exitBtn: {
    padding: "10px 20px",
    background: COLORS.textMuted,
    color: "white",
    border: "none",
    borderRadius: "6px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  cotaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
    marginBottom: "30px",
  },
  cotaCard: {
    padding: "20px",
    borderRadius: "12px",
    border: "1px solid",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  cotaTitle: { margin: 0, fontSize: "16px", color: COLORS.grey75 },
  inputGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: "bold",
  },
  inlineInput: {
    padding: "8px",
    borderRadius: "6px",
    border: `1px solid ${COLORS.dark}`,
    width: "80px",
    fontSize: "16px",
  },
  cotaDesc: { margin: 0, fontSize: "11px", color: COLORS.textMuted },
  addForm: { display: "flex", gap: "10px", flexWrap: "wrap" },
  categorySection: { marginBottom: "40px" },
  categoryHeader: {
    background: COLORS.grey75,
    color: COLORS.white,
    padding: "12px 20px",
    borderRadius: "8px 8px 0 0",
    fontSize: "14px",
    margin: 0,
    letterSpacing: "1px",
  },
  itemsList: {
    background: COLORS.white,
    borderRadius: "0 0 8px 8px",
    border: `1px solid ${COLORS.grey10}`,
    borderTop: "none",
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "2fr 3fr 1.5fr",
    alignItems: "center",
    gap: "20px",
    padding: "15px 20px",
    borderBottom: `1px solid $COLORS.grey10}`,
  },
  itemMainInfo: { display: "flex", flexDirection: "column" },
  itemName: { fontSize: "15px", color: COLORS.grey75 },
  itemSub: {
    fontSize: "11px",
    color: COLORS.grey50,
    textTransform: "uppercase",
  },
  itemConfigs: {
    display: "flex",
    gap: "15px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  configField: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    color: COLORS.textMuted,
  },
  numInput: {
    width: "50px",
    padding: "5px",
    borderRadius: "4px",
    border: `1px solid ${COLORS.grey25}`,
  },
  smallSelect: {
    padding: "5px",
    borderRadius: "4px",
    border: `1px solid ${COLORS.grey25}`,
    fontSize: "12px",
  },
  itemActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "15px",
  },
  statusBtn: {
    border: "none",
    padding: "5px 10px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: "bold",
    cursor: "pointer",
    width: "70px",
  },
  switch: {
    position: "relative",
    display: "inline-block",
    width: "120px",
    height: "28px",
    cursor: "pointer",
  },
  switchInput: {
    opacity: 0,
    width: 0,
    height: 0,
  },
  slider: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: "20px",
    transition: ".3s",
    display: "flex",
    alignItems: "center",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
  sliderBall: {
    position: "absolute",
    height: "20px",
    width: "24px",
    left: "0px",
    bottom: "4px",
    backgroundColor: "white",
    borderRadius: "15px",
    transition: ".3s",
    boxShadow: `0 8px 16px ${COLORS.shadow}`,
  },
  sliderText: {
    position: "absolute",
    color: "white",
    fontSize: "10px",
    fontWeight: "bold",
    pointerEvents: "none",
    transition: ".3s",
    textShadow: `0 8px 16px ${COLORS.shadow}`,
  },
    table: { width: '100%', borderCollapse: 'collapse', marginTop: '10px' },
    thr: { textAlign: 'left', borderBottom: '2px solid #eee', color: '#666', fontSize: '14px' },
    tr: { borderBottom: '1px solid #f5f5f5', fontSize: '13px' },
    td: { padding: '12px 8px' }
};
